-- PoolOps · Initial Schema Migration
-- Spec §2 (Data Models) + §11.1 (Performance Indexes)
-- Version 1.0 · April 2026 · MVP Scope
--
-- Tables: profiles, companies, chemical_products, chemical_stock,
--         customers, pools, service_plans, jobs, service_records,
--         booking_requests, inbox_items, notifications,
--         audit_log, sync_queue
--
-- Run on a fresh Supabase project. Requires Supabase Auth (auth.users) to exist.
-- All IDs are UUIDs generated by the database (gen_random_uuid()).
-- All timestamps are UTC (timestamptz).

-- ============================================================
-- EXTENSIONS
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- ENUM TYPES
-- ============================================================

CREATE TYPE user_role          AS ENUM ('technician', 'pool_owner', 'admin');
CREATE TYPE company_plan       AS ENUM ('solo', 'pro', 'business');
CREATE TYPE chemical_unit      AS ENUM ('ml', 'L', 'g', 'kg', 'tabs');
CREATE TYPE pool_type_enum     AS ENUM ('chlorine', 'salt', 'mineral', 'freshwater');
CREATE TYPE surface_type_enum  AS ENUM ('concrete', 'fibreglass', 'vinyl', 'tiles', 'pebblecrete', 'other');
CREATE TYPE indoor_outdoor     AS ENUM ('indoor', 'outdoor');
CREATE TYPE service_frequency  AS ENUM ('weekly', 'fortnightly', 'monthly', 'custom');
CREATE TYPE job_status         AS ENUM ('pending', 'in_progress', 'complete', 'cancelled');
CREATE TYPE booking_reason     AS ENUM ('water_issue', 'extra_routine', 'event_prep', 'equipment_problem', 'other');
CREATE TYPE booking_status     AS ENUM ('pending', 'confirmed', 'cancelled');
CREATE TYPE inbox_type         AS ENUM ('booking_request', 'flagged_reading');
CREATE TYPE sync_item_type     AS ENUM ('JOB_COMPLETE', 'JOB_START', 'PHOTO_UPLOAD');
CREATE TYPE sync_item_status   AS ENUM ('pending', 'processing', 'completed', 'failed');

-- ============================================================
-- TABLE: companies
-- §2.3 — created before profiles because profiles has a FK to companies
-- ============================================================
-- JSONB schemas:
--   report_branding: { logo_on_pdf: bool, include_technician_name: bool,
--                      include_dosage_details: bool, include_lsi: bool }
--   service_defaults: { ph: {min, max}, chlorine: {min, max},
--                       alkalinity: {min, max}, calcium: {min, max},
--                       stabiliser: {min, max} }

CREATE TABLE companies (
    id                      uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    name                    text        NOT NULL,
    email                   text,
    phone                   text,
    address                 text,
    logo_url                text,
    plan                    company_plan NOT NULL DEFAULT 'solo',
    stripe_customer_id      text,
    stripe_subscription_id  text,
    report_branding         jsonb       NOT NULL DEFAULT '{
        "logo_on_pdf": true,
        "include_technician_name": true,
        "include_dosage_details": false,
        "include_lsi": true
    }'::jsonb,
    service_defaults        jsonb       NOT NULL DEFAULT '{
        "ph":         {"min": 7.2, "max": 7.6},
        "chlorine":   {"min": 1.0, "max": 3.0},
        "alkalinity": {"min": 80,  "max": 120},
        "calcium":    {"min": 200, "max": 400},
        "stabiliser": {"min": 30,  "max": 50}
    }'::jsonb,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- TABLE: profiles
-- §2.1 — extends Supabase Auth (auth.users) with application fields
-- ============================================================
-- JSONB schema:
--   notification_prefs: { schedule_changes: bool, low_stock: bool,
--                         office_messages: bool, sms_schedule_changes: bool }
--   Technician defaults: all true except sms_schedule_changes (false)
--   Pool owner prefs managed separately (pool_customer_prefs — future table)

CREATE TABLE profiles (
    id                  uuid        PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email               text        NOT NULL UNIQUE,
    role                user_role   NOT NULL,
    -- NULL for pool_owner — pool owners link to a company via customers table
    company_id          uuid        REFERENCES companies(id) ON DELETE SET NULL,
    full_name           text        NOT NULL,
    phone               text,
    push_token          text,
    notification_prefs  jsonb       NOT NULL DEFAULT '{
        "schedule_changes":     true,
        "low_stock":            true,
        "office_messages":      true,
        "sms_schedule_changes": false
    }'::jsonb,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- TABLE: chemical_products
-- §2.6 — products configured per company for the treatment entry dropdown
-- ============================================================

CREATE TABLE chemical_products (
    id                      uuid            PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id              uuid            NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    name                    text            NOT NULL,
    unit                    chemical_unit   NOT NULL,
    stock_alert_threshold   numeric,
    sort_order              integer         NOT NULL DEFAULT 0,
    active                  boolean         NOT NULL DEFAULT true,
    UNIQUE (company_id, name)
);

-- ============================================================
-- TABLE: chemical_stock
-- §2.7 — current stock levels per company per product
-- ============================================================

CREATE TABLE chemical_stock (
    id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id      uuid        NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    product_id      uuid        NOT NULL REFERENCES chemical_products(id) ON DELETE CASCADE,
    current_amount  numeric     NOT NULL DEFAULT 0 CHECK (current_amount >= 0),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (company_id, product_id)
);

-- ============================================================
-- TABLE: customers
-- §2.8 — pool owner contact and service relationship per company
-- ============================================================

CREATE TABLE customers (
    id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id      uuid        NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    -- NULL until owner accepts invite and creates their auth account
    user_id         uuid        REFERENCES auth.users(id) ON DELETE SET NULL,
    first_name      text        NOT NULL,
    last_name       text        NOT NULL,
    email           text        NOT NULL,
    phone           text,
    address         text        NOT NULL,
    invite_token    text        UNIQUE,
    invite_sent_at  timestamptz,
    active          boolean     NOT NULL DEFAULT true,
    created_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (company_id, email)
);

-- ============================================================
-- TABLE: pools
-- §2.9 — one pool per customer in MVP; schema supports multiple in v2
-- ============================================================
-- JSONB schema:
--   target_overrides: same shape as service_defaults — per-pool range overrides (v2; null = use company defaults)

CREATE TABLE pools (
    id               uuid                PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_id      uuid                NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    -- Denormalised for RLS — avoids a join on every policy check
    company_id       uuid                NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    volume_litres    numeric             NOT NULL CHECK (volume_litres > 0),
    pool_type        pool_type_enum      NOT NULL,
    surface_type     surface_type_enum,
    indoor_outdoor   indoor_outdoor,
    equipment_notes  text,
    gate_access      text,
    -- Shown amber to technician on pool brief
    warnings         text,
    -- Array of chemical_products.id used at this pool
    chemical_products uuid[]             NOT NULL DEFAULT '{}',
    -- Per-pool target range overrides (v2); null = use company defaults
    target_overrides jsonb,
    created_at       timestamptz         NOT NULL DEFAULT now(),
    updated_at       timestamptz         NOT NULL DEFAULT now()
);

-- ============================================================
-- TABLE: service_plans
-- §2.10 — recurring schedule for a pool
-- ============================================================

CREATE TABLE service_plans (
    id              uuid                PRIMARY KEY DEFAULT gen_random_uuid(),
    pool_id         uuid                NOT NULL REFERENCES pools(id) ON DELETE CASCADE,
    -- Denormalised for RLS
    company_id      uuid                NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    technician_id   uuid                NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
    frequency       service_frequency   NOT NULL,
    -- 0=Sunday … 6=Saturday; NULL for monthly/custom frequencies
    day_of_week     integer             CHECK (day_of_week BETWEEN 0 AND 6),
    active          boolean             NOT NULL DEFAULT true,
    created_at      timestamptz         NOT NULL DEFAULT now()
);

-- ============================================================
-- TABLE: jobs
-- §2.11 — one row per scheduled pool visit; generated daily by cron
-- ============================================================

CREATE TABLE jobs (
    id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id      uuid        NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    pool_id         uuid        NOT NULL REFERENCES pools(id) ON DELETE RESTRICT,
    technician_id   uuid        NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
    scheduled_date  date        NOT NULL,
    -- 1-indexed position in technician run sheet
    route_order     integer     NOT NULL DEFAULT 1,
    status          job_status  NOT NULL DEFAULT 'pending',
    started_at      timestamptz,
    completed_at    timestamptz,
    -- true for one-off visits created from booking requests
    is_extra        boolean     NOT NULL DEFAULT false,
    created_at      timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- TABLE: service_records
-- §2.12 — immutable record of a completed job; one row per job
-- ============================================================
-- JSONB schemas:
--   readings: {
--     ph:         { value: number, status: "good"|"low"|"high" },
--     chlorine:   { value: number, status: "good"|"low"|"high" },
--     alkalinity: { value: number, status: "good"|"low"|"high" },
--     calcium:    { value: number, status: "good"|"low"|"high" },
--     stabiliser: { value: number, status: "good"|"low"|"high" },
--     custom: [{ label: string, value: number, unit: string }]
--   }
--   treatments: [
--     { product_id: uuid, product_name: string, unit: string,
--       recommended: number, actual: number }
--   ]
--   photo_urls: { before: string|null, after: string|null, additional: string[] }
--
-- SECURITY NOTE: office_note is NEVER returned in owner-facing API responses.
-- Enforce at the API layer (not just RLS) per spec §2.12.

CREATE SEQUENCE IF NOT EXISTS service_record_seq START 1;

CREATE TABLE service_records (
    id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    -- Human-readable ref: SR-YYYY-NNNN — generated at insert time in application layer
    ref              text        UNIQUE,
    job_id           uuid        NOT NULL UNIQUE REFERENCES jobs(id) ON DELETE RESTRICT,
    pool_id          uuid        NOT NULL REFERENCES pools(id) ON DELETE RESTRICT,
    -- Denormalised for RLS and query performance
    company_id       uuid        NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
    technician_id    uuid        NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
    customer_id      uuid        NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
    completed_at     timestamptz NOT NULL,
    duration_seconds integer,
    readings         jsonb       NOT NULL,
    lsi_score        numeric(5,2) NOT NULL,
    lsi_label        text        NOT NULL,
    treatments       jsonb       NOT NULL,
    photo_urls       jsonb,
    customer_note    text,
    -- SECURITY: NEVER expose this field in pool owner responses
    office_note      text,
    is_flagged       boolean     NOT NULL DEFAULT false,
    flagged_readings text[],
    report_sent_at   timestamptz,
    -- Locked on creation; only office_note editable by admin post-lock
    locked           boolean     NOT NULL DEFAULT true
);

-- ============================================================
-- TABLE: booking_requests
-- §2.15 — visit requests submitted by pool owners via M18
-- ============================================================

CREATE TABLE booking_requests (
    id                  uuid            PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_id         uuid            NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    company_id          uuid            NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    pool_id             uuid            NOT NULL REFERENCES pools(id) ON DELETE CASCADE,
    reason              booking_reason  NOT NULL,
    description         text,
    photo_url           text,
    status              booking_status  NOT NULL DEFAULT 'pending',
    -- Set when admin confirms via POST /admin/inbox/:id/confirm-visit
    confirmed_job_id    uuid            REFERENCES jobs(id) ON DELETE SET NULL,
    created_at          timestamptz     NOT NULL DEFAULT now(),
    resolved_at         timestamptz
);

-- ============================================================
-- TABLE: inbox_items
-- §2.16 — unified admin inbox; aggregates booking_requests and flagged_readings
-- ============================================================
-- reference_id is a polymorphic FK:
--   type='booking_request'  → booking_requests.id
--   type='flagged_reading'  → service_records.id
-- Enforced at application layer (Postgres lacks native polymorphic FKs).

CREATE TABLE inbox_items (
    id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id      uuid        NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    type            inbox_type  NOT NULL,
    -- Polymorphic: FK to booking_requests or service_records depending on type
    reference_id    uuid        NOT NULL,
    -- Denormalised for query performance (avoids join on inbox queries)
    customer_id     uuid        NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    resolved        boolean     NOT NULL DEFAULT false,
    created_at      timestamptz NOT NULL DEFAULT now(),
    resolved_at     timestamptz
);

-- ============================================================
-- TABLE: notifications
-- §2.17 — in-app notification log for mobile users
-- ============================================================
-- type values: service_complete, visit_confirmed, schedule_change,
--              low_stock, flagged_reading, office_message, request_received

CREATE TABLE notifications (
    id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    type            text        NOT NULL,
    title           text        NOT NULL,
    body            text        NOT NULL,
    -- ID of related record (service_record, job, booking_request, etc.)
    reference_id    uuid,
    read            boolean     NOT NULL DEFAULT false,
    created_at      timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- TABLE: audit_log
-- Compliance + change-tracking log for all significant data mutations.
-- Populated by application layer triggers on sensitive tables.
-- ============================================================

CREATE TABLE audit_log (
    id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id  uuid        REFERENCES companies(id) ON DELETE SET NULL,
    -- NULL for system-initiated events (cron, background jobs)
    user_id     uuid        REFERENCES auth.users(id) ON DELETE SET NULL,
    table_name  text        NOT NULL,
    record_id   uuid        NOT NULL,
    action      text        NOT NULL CHECK (action IN ('INSERT', 'UPDATE', 'DELETE')),
    -- Previous state before mutation (null for INSERT)
    old_data    jsonb,
    -- New state after mutation (null for DELETE)
    new_data    jsonb,
    created_at  timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- TABLE: sync_queue
-- Server-side record of offline sync payloads submitted by mobile clients.
-- Mobile app queues failed requests in expo-sqlite; on reconnect, these
-- are sent to the API for server-side processing and deduplication.
-- Retry logic: max 5 retries, exponential backoff (1s/2s/4s/8s/16s).
-- ============================================================

CREATE TABLE sync_queue (
    id              uuid                PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id      uuid                NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    user_id         uuid                NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    type            sync_item_type      NOT NULL,
    payload         jsonb               NOT NULL,
    status          sync_item_status    NOT NULL DEFAULT 'pending',
    retry_count     integer             NOT NULL DEFAULT 0 CHECK (retry_count >= 0),
    next_retry_at   timestamptz         NOT NULL DEFAULT now(),
    created_at      timestamptz         NOT NULL DEFAULT now(),
    processed_at    timestamptz
);

-- ============================================================
-- PERFORMANCE INDEXES  (§11.1 — all 6 required indexes)
-- ============================================================

-- 1. Run sheet query: technician's jobs for a date filtered by status
CREATE INDEX idx_jobs_technician_date_status
    ON jobs (technician_id, scheduled_date, status);

-- 2. Admin service record list: company ordered by newest first
CREATE INDEX idx_service_records_company_completed
    ON service_records (company_id, completed_at DESC);

-- 3. Customer service history: customer ordered by newest first
CREATE INDEX idx_service_records_customer_completed
    ON service_records (customer_id, completed_at DESC);

-- 4. Flagged reading filter: fast scan for company's flagged records
CREATE INDEX idx_service_records_company_flagged
    ON service_records (company_id, is_flagged);

-- 5. Admin inbox query: company's unresolved inbox items
CREATE INDEX idx_inbox_items_company_resolved
    ON inbox_items (company_id, resolved);

-- 6. Notification list: user's unread notifications ordered by newest first
CREATE INDEX idx_notifications_user_read_created
    ON notifications (user_id, read, created_at DESC);

-- ============================================================
-- SUPPLEMENTARY INDEXES
-- Not required by §11.1 but critical for FK traversal performance
-- on high-frequency query paths.
-- ============================================================

CREATE INDEX idx_profiles_company         ON profiles (company_id);
CREATE INDEX idx_chemical_products_company ON chemical_products (company_id);
CREATE INDEX idx_chemical_stock_product   ON chemical_stock (product_id);
CREATE INDEX idx_customers_company        ON customers (company_id);
CREATE INDEX idx_customers_user           ON customers (user_id);
CREATE INDEX idx_pools_customer           ON pools (customer_id);
CREATE INDEX idx_pools_company            ON pools (company_id);
CREATE INDEX idx_service_plans_pool       ON service_plans (pool_id);
CREATE INDEX idx_service_plans_technician ON service_plans (technician_id);
CREATE INDEX idx_jobs_company_date        ON jobs (company_id, scheduled_date);
CREATE INDEX idx_jobs_pool                ON jobs (pool_id);
CREATE INDEX idx_service_records_job      ON service_records (job_id);
CREATE INDEX idx_booking_requests_company ON booking_requests (company_id, status);
CREATE INDEX idx_sync_queue_status        ON sync_queue (status, next_retry_at)
    WHERE status IN ('pending', 'failed');
CREATE INDEX idx_audit_log_table_record   ON audit_log (table_name, record_id);

-- ============================================================
-- updated_at TRIGGER FUNCTION
-- ============================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_companies_updated_at
    BEFORE UPDATE ON companies
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_profiles_updated_at
    BEFORE UPDATE ON profiles
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_pools_updated_at
    BEFORE UPDATE ON pools
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_chemical_stock_updated_at
    BEFORE UPDATE ON chemical_stock
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
